[package]
name = "exmc_tree"
version = "0.1.0"
edition = "2021"

[lib]
name = "exmc_tree"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "~0.36"
rand = "0.8"
rand_xoshiro = "0.6"
